// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config/secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: Secrets.firebaseApiKeyBrowser,
        appId: '1:256451027870:web:795b1820784ef1164f2c8f',
        messagingSenderId: '256451027870',
        projectId: 'lotus-418f7',
        authDomain: 'lotus-418f7.firebaseapp.com',
        storageBucket: 'lotus-418f7.firebasestorage.app',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: Secrets.firebaseApiKeyAndroid,
        appId: '1:256451027870:android:f4228f3c871fd6894f2c8f',
        messagingSenderId: '256451027870',
        projectId: 'lotus-418f7',
        storageBucket: 'lotus-418f7.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: Secrets.firebaseApiKeyIos,
        appId: '1:256451027870:ios:20a28817285580294f2c8f',
        messagingSenderId: '256451027870',
        projectId: 'lotus-418f7',
        storageBucket: 'lotus-418f7.firebasestorage.app',
        iosBundleId: 'com.example.rotus',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: Secrets.firebaseApiKeyMacos,
        appId: '1:256451027870:ios:20a28817285580294f2c8f',
        messagingSenderId: '256451027870',
        projectId: 'lotus-418f7',
        storageBucket: 'lotus-418f7.firebasestorage.app',
        iosBundleId: 'com.example.rotus',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: Secrets.firebaseApiKeyWindows,
        appId: '1:256451027870:web:8f92f242957797074f2c8f',
        messagingSenderId: '256451027870',
        projectId: 'lotus-418f7',
        authDomain: 'lotus-418f7.firebaseapp.com',
        storageBucket: 'lotus-418f7.firebasestorage.app',
      );
}
